### ISSUE TITLE
step 13 add package

### ISSUE THREAD

**Issue by rvegele** [ExtendRealityLtd/VRTK.Tutorials.VRBowling#5]
Add to manifest.json
"io.extendreality.tilia.interactions.interactables.unity": "1.4.0",
(or whichever the newest version)

**Comment by thestonefox** [comment]
You don't need to do this because it's already covered in step 12 by

`...now let's just set up our Interactors by following the Adding An Interactor how-to guide.`

The `Adding An Interactor` has a prerequisite of adding that package.
